// Generated by wangdxh

package snmplib

import "github.com/soniah/gosnmp"

// https://blog.51cto.com/13769225/2121431 网络拓扑
// https://blog.51cto.com/13769225/2121928
type oidtablecolums struct {
	Oid        string
	Colums     int
	Structtype interface{}
}



//iftableType:           &oidtablecolums{".1.3.6.1.2.1.2.2.1.", 22, IfTable{}},

var mapnameoidtable map[string]*oidtablecolums = map[string]*oidtablecolums{
{% for seq in seqlist %}
	"{{ seq.Name}}" : &oidtablecolums{ "{{seq.Entryoid}}", {{seq.Children|length}}, {{seq.Name|title}}{}},  {% endfor %}
}


{% for seq in seqlist %}
type {{seq.Name|title}} struct {
    {% for son in seq.Children%}
{{son.Name|title}}  {{son.Gotype}}  `snmp:"{{son.Mibtype}}"`  {% endfor %}
}

func Get{{seq.Name}}(g *gosnmp.GoSNMP) (tablist []{{seq.Name|title}}, err error) {
	ret, err := getInfo(g, "{{seq.Name}}")
	if err != nil {
		return
	}
	for _, val := range ret {
		tablist = append(tablist, val.({{seq.Name|title}}))
	}
	return
}
{% endfor %}


var mapnameoid map[string]string = map[string]string{
//sysservices:  ".1.3.6.1.2.1.1.7.0", // 0110 第二层和三层
{% for obj in objlist %}
	"{{obj.Name}}" : "{{obj.Entryoid|add:".0"}}", {% endfor %}
}

{% for obj in objlist %}
func Get{{obj.Name}}(g *gosnmp.GoSNMP) ( {{obj.Gotype}}, error) {
	ret, err := getitemvalue(g, "{{obj.Name}}")
	if err == nil {
		return ret.({{obj.Gotype}}), nil
	}
	return {% if obj.Gotype=="int" %} 0 {% else %} "" {% endif %}, err
}
{% endfor %}