// the file is generated by gowalle at {% now "Mon Jan 2 15:04:05 -0700 CST 2006"%}
package {{package}}

{% if importmap|length > 0 %} 
import (
	{% for key,name in importmap %}
	"{{key}}" {% endfor %}
)
{% endif %}


type {{TableInfo.Name|title}} struct {
	{% for item in TableInfo.Itemlist %}
	{{item.Field|title}} {{item.GoType}} `json:"{{item.Field}}" db:"{{item.Field}}" dbtype:"{{item.Type}},{{item.Key}}"` {% endfor %}    
}

// insert delete update select

